---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: compserv-service-account-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: compserv-service-account-role
subjects:
  - kind: ServiceAccount
    name: compserv-sa
    namespace: compserv
roleRef:
  kind: Role
  name: compserv-service-account-role
  apiGroup: rbac.authorization.k8s.io
